run:
  concurrency: 1
  skip-dirs:
    - vendor
  timeout: 3m
  modules-download-mode: vendor
  allow-parallel-runners: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - typecheck
    - unused
    - vet
    - stylecheck
    - gocyclo
    - gofmt
    - gosimple
    - ineffassign
    - asciicheck
    - bodyclose
    - dogsled
    - exportloopref
    - gocognit
    - gocritic
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    ignore: bytes:.*,io:Close|Write

  lll:
    line-length: 180

  stylecheck:
    pkg_name: false
    camel_name: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - stylecheck
        - unused
